### ISSUE TITLE
SLow problem

### ISSUE THREAD

**Issue by andiconda** [ravijo/kinect_anywhere#1]
I run it in one local wifi.but it is very slow to play RGBD ? do you have some solution for it ?

**Comment by ravijo** [comment]
@alexchauncy: The major concern while developing this tool was to receive high quality of point cloud data in realtime. You need to understand that the amount of point cloud data is too much to transfer in realtime using WiFi.

In fact here in my environment, I am using Ethernet wire (CAT 6) in 1 GBPS LAN connection. The average data transfer speed (RGB, RGBD and Body Data is selected) is approximately 800 MBPS and I can verify visually that it is realtime by visualizing it.

Hence if you need realtime data, I strongly recommend you to use high speed Ethernet.

**Comment by andiconda** [comment]
Cool Merci

**Comment by ravijo** [comment]
[Documentation](https://github.com/ravijo/kinect_anywhere#note) has been updated with extra information.
