### ISSUE TITLE
cannot launch node of type in package can't locate node in package?

### ISSUE THREAD

**Issue by andiconda** [ravijo/kinect_anywhere#3]
core service [/rosout] found
ERROR: cannot launch node of type [kinect_anywhere/body_frame]: can't locate node [body_frame] in package [kinect_anywhere]
ERROR: cannot launch node of type [kinect_anywhere/color_frame]: can't locate node [color_frame] in package [kinect_anywhere]
ERROR: cannot launch node of type [kinect_anywhere/point_cloud]: can't locate node [point_cloud] in package [kinect_anywhere]
 do you know what happened, I done chmod. still can not work

**Comment by ravijo** [comment]
Have you compiled the package? It seems that executables are not available yet.

```
cd ~/ros_ws
source devel/setup.bash
catkin_make
```

**Comment by andiconda** [comment]
yes <i have

**Comment by ravijo** [comment]
I just cloned the repository and moved `kinect_anywhere` folder which is kept inside Linux folder. I moved it to `ros_ws`. In my computer, the file structure looks following-
```
ravi@home:~/ros_ws/src/kinect_anywhere$ tree
.
├── cmake
│   └── FindZeroMQ.cmake
├── CMakeLists.txt
├── launch
│   └── kinect_anywhere.launch
├── msg
│   ├── BodyFrame.msg
│   ├── Body.msg
│   └── JointPositionAndState.msg
├── package.xml
└── src
    ├── body_frame.cpp
    ├── color_frame.cpp
    └── point_cloud.cpp

4 directories, 10 files
```
I used the same commands as said earlier-

```
cd ~/ros_ws
source devel/setup.bash
catkin_make
source devel/setup.bash
roslaunch kinect_anywhere kinect_anywhere.launch color:=true body:=true pointcloud:=true kinect_frame:=base
```
It worked without any issues! Are you sure that you `source` the appropriate file? If the issue still persists, please share more information.

**Comment by andiconda** [comment]
It works on ubuntu.
 ubuntu PC connects to windows PC. means the same local network？ cable connect to the same switch or same router？Or directly  a cable one side with windows PC, another side with Ubuntu PC?

**Comment by ravijo** [comment]
@alexchauncy: Any network configuration is fine. _The only condition is that Windows and Ubuntu computer must be able to communicate with each other_ (`ping` must work from both the machine).

In my laboratory, **I directly connect Windows PC to Ubuntu PC using an ethernet wire**. In this case, I need to set up local IP addresses for both computers. I assume that you are capable of this networking. As far as I remember, I have disabled the firewall on Windows PC. This can easily be known by using `ping` command. Even after assigning local IP to both the computers, if you aren't able to ping, then you should try disabling the firewall.

**Comment by andiconda** [comment]
OK clearly thank you
