### ISSUE TITLE
rostopic echo cannot work?

### ISSUE THREAD

**Issue by andiconda** [ravijo/kinect_anywhere#4]
At ubuntu, rostopic list. i can see:
/kinect_anywhere/body_frame/bodies
/kinect_anywhere/color_frame/camera_info
/kinect_anywhere/color_frame/image
/kinect_anywhere/color_frame/image/compressed
/kinect_anywhere/color_frame/image/compressed/parameter_descriptions
/kinect_anywhere/color_frame/image/compressed/parameter_updates
/kinect_anywhere/color_frame/image/compressedDepth
/kinect_anywhere/color_frame/image/compressedDepth/parameter_descriptions
/kinect_anywhere/color_frame/image/compressedDepth/parameter_updates
/kinect_anywhere/color_frame/image/theora
/kinect_anywhere/color_frame/image/theora/parameter_descriptions
/kinect_anywhere/color_frame/image/theora/parameter_updates
/rosout
/rosout_agg

but rostopic echo /kinect_anywhere/body_frame/bodies, nothing happened.(they can ping each other and kinect can work well on windows)
why?

**Comment by andiconda** [comment]
rostopic echo -p /kinect_anywhere/color_frame/image/compressed  > log_1.txt
nothing recorded

**Comment by ravijo** [comment]
> rostopic echo /kinect_anywhere/body_frame/bodies, nothing happened

It clearly indicates that nodes at the Ubuntu side are not able to receive the data from the Windows side. You can try following-

- Are you sure that `kinect_anywhere` is running on the Windows side? 
- Can you please check the notification bar (which is located at the bottom right side of the Windows) and make sure that `kinect_anywhere` is turning into the green color icon?
- Stop `roslaunch kinect_anywhere kinect_anywhere.launch` then start  `kinect_anywhere` on windows. Make sure to select at least one data in `kinect_anywhere` software. Finally run `roslaunch kinect_anywhere kinect_anywhere.launch`

**Comment by ravijo** [comment]
One more thing, are you setting the correct `host` parameter while invoking `roslaunch kinect_anywhere kinect_anywhere.launch`?

Please read the **Linux** section [here](https://github.com/ravijo/kinect_anywhere#steps-to-run).
- `host`: String variable to set IP address of the Windows PC

To set the `host` parameter, you can do any one from the following-

- You can either edit the value of `host` in [kinect_anywhere.launch](https://github.com/ravijo/kinect_anywhere/blob/master/Linux/kinect_anywhere/launch/kinect_anywhere.launch#L12) file
- Provide `host` parameter while  invoking as shown below - 
```
roslaunch kinect_anywhere kinect_anywhere.launch color:=true body:=true pointcloud:=true kinect_frame:=base host:=192.168.abc.xyz
```

Hope it helps!

**Comment by andiconda** [comment]
It works. only one thing! I forget to change the host IP address at the launch document.
Thank you

**Comment by ravijo** [comment]
I have added this information in `README.md` so that others don't miss it.
