### ISSUE TITLE
Kinect V1

### ISSUE THREAD

**Issue by GricksNT** [ravijo/kinect_anywhere#5]
is there any way for this to work with kinect v1 ?

**Comment by ravijo** [comment]
@ahmedai91 

> is there any way for this to work with kinect v1 ?

Short answer: No

Long answer: You need to edit the code at Windows side. This package uses Kinect v2 SDK. So first you need to install Kinect v1 SDK and then make changes in the following file:
[kinect_anywhere/Windows/Kinect Anywhere/Kinect Anywhere/Kinect Anywhere.cs ](https://github.com/ravijo/kinect_anywhere/blob/334040c0b3420915f90c8172908410d7fc8c349f/Windows/Kinect%20Anywhere/Kinect%20Anywhere/Kinect%20Anywhere.cs)

For example, you have to edit frame acquisition [here](https://github.com/ravijo/kinect_anywhere/blob/334040c0b3420915f90c8172908410d7fc8c349f/Windows/Kinect%20Anywhere/Kinect%20Anywhere/Kinect%20Anywhere.cs#L115-L117) and many other lines inside the same file.

I wonder why you are using Kinect v1 thought. Is it still in the market? 

Anyway, I hope you can make appropriate changes in the code to make this package compatible with Kinect v1.

Cheers!
