### ISSUE TITLE
Unable to build with catkin-Potential Ros version issue

### ISSUE THREAD

**Issue by johnnypipey** [ravijo/kinect_anywhere#6]
Not sure if I have done something incorrect but I am unable to build the Linux part, I have the kinect_anywhere file with cmake, launch,msg,SRC etc but when I run catkin_make in the work space I got a load of errors the final being:Invoking -j4 -14 failed
What version of Ros is this package designed for because I'm running noetic and I wonder if that is the issue
Thank you

**Comment by ravijo** [comment]
@johnnypipey 

Sorry to hear that you faced an installation issue. It is exactly clear what is the problem you received. 

- Can you please share the complete output reported at terminal?

Installing the Linux (ROS) part is easy. You need to move [kinect_anywhere](https://github.com/ravijo/kinect_anywhere/tree/master/Linux) folder to your workspace as shown below:
```
ravi@dell:~/ros_ws$ tree -a
.
├── build
│   └── omitted to keep the post shorter
├── .catkin_workspace
├── devel
│   └── omitted to keep the post shorter
└── src
    ├── CMakeLists.txt -> /opt/ros/melodic/share/catkin/cmake/toplevel.cmake
    └── kinect_anywhere
        ├── cmake
        │   └── FindZeroMQ.cmake
        ├── CMakeLists.txt
        ├── launch
        │   └── kinect_anywhere.launch
        ├── msg
        │   ├── BodyFrame.msg
        │   ├── Body.msg
        │   └── JointPositionAndState.msg
        ├── package.xml
        └── src
            ├── body_frame.cpp
            ├── color_frame.cpp
            └── point_cloud.cpp
```

>  What version of Ros is this package designed for

As mentioned in the 2nd point of [Note](https://github.com/ravijo/kinect_anywhere#note), the application was tested on ROS Indigo. Just now, I compiled it with ROS Melodic, the compilation went well. So I believe that it should work with ROS1.

You may have to change `emplace_back` with `push_back` in [line number 145 of point_cloud.cpp](https://github.com/ravijo/kinect_anywhere/blob/334040c0b3420915f90c8172908410d7fc8c349f/Linux/kinect_anywhere/src/point_cloud.cpp#L145) if you see this error in terminal.

Moving from ROS1 to ROS2 (Noetic) should be straightforward. The package may require minimal tweak though!

Let me know if the problem persist.

**Comment by ravijo** [comment]
Closing this issue as no further comments have been received. However, feel free to comment if the problem still exists.
